id: IDDA7F69E
initial_creation_type: ebook
source_metadata:
  id: RDI-SK-02
  title: དཔལ་ལྡན་ཤངས་པའི་བླ་མ་རིམ་བྱོན་གྱི་རྣམ་ཐར་མུ་ཏིག་ཕྲེང་མཛེས།
  author: མཛད་པ་པོ། ཏཱ་ར་ནཱ་ཐ། ཙིཏྟ། མུག་མཆོག་པ།
  authors: &id001
  - མཛད་པ་པོ། ཏཱ་ར་ནཱ་ཐ། ཙིཏྟ། མུག་མཆོག་པ།
  sku: RDI-SK-02
  cover: RDI-SK-02.jpeg
  volume: {}
  title_source: epub:dc:title:ambiguous-layer
ebook_metadata:
  title: དཔལ་ལྡན་ཤངས་པའི་བླ་མ་རིམ་བྱོན་གྱི་རྣམ་ཐར་མུ་ཏིག་ཕྲེང་མཛེས།
  authors: *id001
  sku: RDI-SK-02
  cover: RDI-SK-02.jpeg
layers:
- Author
- BookTitle
- Chapter
- Citation
- Commentary
- Sabche
- Tsawa
- Yigchung
